version: 0.2

env:
  variables:
    SONAR_PROJECT_KEY: "DE3P14_Dee_Transport_clouddevops"
    SONAR_QUBE_URL: "http://sonarcloud.io"
    SONARCLOUD_TOKEN: "eea5996cf401092a90def01df27804a760cdddb1"
phases:
  install:
    runtime-versions:
      python: 3.10
      java: corretto17
    commands:
    # Install dependencies
    - echo Installing dependencies...
    - pip install -r requirements.txt
    - pip install pylint sonar-scanner

  pre_build:
    commands:
    # Pylint code quality check
    - echo Running Pylint...
    - pylint --exit-zero busapp managements > pylint-report.txt

  build:
    commands:
    # SonarCloud analysis
    - >
      sonar-scanner -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONARCLOUD_TOKEN -Dsonar.python.pylint.reportPaths=pylint-report.txt # Include any additional SonarCloud parameters here #magic___^_^___line
artifacts:
  files:
  - pylint-report.txt

cache:
  paths:
  - '*/target/**/*'
