# Generated by Django 4.2.11 on 2024-04-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0016_ticket_bus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='choices',
        ),
        migrations.AlterField(
            model_name='bus',
            name='arrival_city',
            field=models.CharField(choices=[('Dublin', 'Dublin'), ('Cork', 'Cork'), ('Galway', 'Galway'), ('Limerick', 'Limerick'), ('Waterford', 'Waterford'), ('Kilkenny', 'Kilkenny'), ('Wexford', 'Wexford'), ('Donegal', 'Donegal'), ('Derry', 'Derry'), ('Sligo', 'Sligo'), ('Kerry', 'Kerry'), ('Clare', 'Clare'), ('Tipperary', 'Tipperary')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='departure_city',
            field=models.CharField(choices=[('Dublin', 'Dublin'), ('Cork', 'Cork'), ('Galway', 'Galway'), ('Limerick', 'Limerick'), ('Waterford', 'Waterford'), ('Kilkenny', 'Kilkenny'), ('Wexford', 'Wexford'), ('Donegal', 'Donegal'), ('Derry', 'Derry'), ('Sligo', 'Sligo'), ('Kerry', 'Kerry'), ('Clare', 'Clare'), ('Tipperary', 'Tipperary')], max_length=150),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentMethod',
            field=models.CharField(choices=[('VISA', 'VISA'), ('MASTERCARD', 'MASTERCARD'), ('REVOLUT', 'REVOLUT'), ('BANK TRANSFER', 'BANK TRANSFER')], max_length=100),
        ),
        migrations.AlterField(
            model_name='route',
            name='arrival_city',
            field=models.CharField(choices=[('Dublin', 'Dublin'), ('Cork', 'Cork'), ('Galway', 'Galway'), ('Limerick', 'Limerick'), ('Waterford', 'Waterford'), ('Kilkenny', 'Kilkenny'), ('Wexford', 'Wexford'), ('Donegal', 'Donegal'), ('Derry', 'Derry'), ('Sligo', 'Sligo'), ('Kerry', 'Kerry'), ('Clare', 'Clare'), ('Tipperary', 'Tipperary')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='departure_city',
            field=models.CharField(choices=[('Dublin', 'Dublin'), ('Cork', 'Cork'), ('Galway', 'Galway'), ('Limerick', 'Limerick'), ('Waterford', 'Waterford'), ('Kilkenny', 'Kilkenny'), ('Wexford', 'Wexford'), ('Donegal', 'Donegal'), ('Derry', 'Derry'), ('Sligo', 'Sligo'), ('Kerry', 'Kerry'), ('Clare', 'Clare'), ('Tipperary', 'Tipperary')], max_length=150),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pay',
            field=models.IntegerField(choices=[(15, 15), (17, 17)], null=True),
        ),
    ]
